### ISSUE TITLE
libtorch_cpu.so: undefined symbol

### ISSUE THREAD

**Issue by jinxycandotailwhip** [hijkzzz/alpha-zero-gomoku#28]
i have problem with learner_test.py
i tried pytorch1.0 and 1.7, neither can work, 
the error is as followed, can someone take a look
Traceback (most recent call last):
  File "leaner_test.py", line 6, in <module>
    import learner
  File "../src/learner.py", line 16, in <module>
    from neural_network import NeuralNetWorkWrapper
  File "../src/neural_network.py", line 6, in <module>
    import torch
  File "/home/jinxiaoyang/anaconda3/envs/multiAlphaGomoku/lib/python3.6/site-packages/torch/__init__.py", line 197, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/jinxiaoyang/anaconda3/envs/multiAlphaGomoku/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: _ZNK3c1010TensorImpl23shallow_copy_and_detachERKNS_15VariableVersionEb

**Comment by jinxycandotailwhip** [comment]
i can import torch in my own code without error

**Comment by jinxycandotailwhip** [comment]
libtorch and pytorch need to be the same version
