### ISSUE TITLE
_library问题

### ISSUE THREAD

**Issue by tsukasa482** [hijkzzz/alpha-zero-gomoku#36]
我用VS2019用realease模式编译生成后，将生成的文件放入build目录下，最后尝试训练，但出现了下述报错，想询问一下解决方式，python3.8,torch1.12.1,swig4.1.1 

(zero) C:\Users\Science\Desktop\alpha-zero-gomoku-master\test>python learner_test.py train
Traceback (most recent call last):
  File "learner_test.py", line 6, in <module>
    import learner
  File "../src\learner.py", line 14, in <module>
    from library import MCTS, Gomoku, NeuralNetwork
  File "../build\library.py", line 12, in <module>
    import _library
ImportError: DLL load failed while importing _library: 参数错误。

**Comment by tsukasa482** [comment]
Do you have a release version of windows?

**Comment by hijkzzz** [comment]
大概率环境变量问题

**Comment by tsukasa482** [comment]
> 大概率环境变量问题

我把swig，libtorch，cmake都加进环境变量了，还是不太行

**Comment by hijkzzz** [comment]
> > 大概率环境变量问题
> 
> 我把swig，libtorch，cmake都加进环境变量了，还是不太行

把编译目录也加进去

**Comment by tsukasa482** [comment]
> > > 大概率环境变量问题
> > 
> > 
> > 我把swig，libtorch，cmake都加进环境变量了，还是不太行
> 
> 把编译目录也加进去

好像还是不太行，大佬。您是用vs进行编译的吗，不是的话能否告诉我您是用什么编译的

**Comment by pursuingz** [comment]
大佬好，我也遇到了_library的问题，出现了下面的报错，可以请教一下是什么原因吗python3.8,pytorch2.0.0,swig4.1.1,cuda11.8
root@autodl-container-a814498486-f5af7a82:~/autodl-tmp/alpha-zero-gomoku/test# python learner_test.py train
Traceback (most recent call last):
  File "learner_test.py", line 6, in <module>
    import learner
  File "/root/autodl-tmp/alpha-zero-gomoku/test/../src/learner.py", line 14, in <module>
    from library import MCTS, Gomoku, NeuralNetwork
  File "/root/autodl-tmp/alpha-zero-gomoku/test/../src/library.py", line 15, in <module>
    import _library
ModuleNotFoundError: No module named '_library'

**Comment by tsukasa482** [comment]
> 大佬好，我也遇到了_library的问题，出现了下面的报错，可以请教一下是什么原因吗python3.8,pytorch2.0.0,swig4.1.1,cuda11.8 root@autodl-container-a814498486-f5af7a82:~/autodl-tmp/alpha-zero-gomoku/test# python learner_test.py train Traceback (most recent call last): File "learner_test.py", line 6, in import learner File "/root/autodl-tmp/alpha-zero-gomoku/test/../src/learner.py", line 14, in from library import MCTS, Gomoku, NeuralNetwork File "/root/autodl-tmp/alpha-zero-gomoku/test/../src/library.py", line 15, in import _library ModuleNotFoundError: No module named '_library'

把生成的文件放进build文件夹里试试

**Comment by tsukasa482** [comment]
> Do you have a release version of windows?

有的话能借鉴一下吗

**Comment by hijkzzz** [comment]
我上次测试的环境是 CUDA 11.6/PyTorch 1.10/LibTorch 1.10(Pre-cxx11 ABI)/SWIG 4.0.2

**Comment by tsukasa482** [comment]
> 我上次测试的环境是 CUDA 11.6/PyTorch 1.10/LibTorch 1.10(Pre-cxx11 ABI)/SWIG 4.0.2

感觉不是版本问题，是vs的配置生成上的问题

**Comment by tsukasa482** [comment]
linux上环境搭配比较容易，但Windows上比较困难

**Comment by EuJinnLucaShow** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
booki77, @zoignk, @sswastioyono18, @whiznic, @antoniott15, @fukafu585, @zhenghao111, @dcortesf, @lukablue, @MindShen, @0xACE3, @jorshimayor, @nevoband, @tommyliu1114, @Saif807380, @balogic, @ajuare8, @Madhu009, @abfedena, @phunguyen19
